// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorApi.Services;

#nullable disable

namespace MonitorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205044004_init22")]
    partial class init22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ModbusConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DataMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DataPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endianness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Offset")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("RegisterStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataPointId")
                        .IsUnique();

                    b.ToTable("ModbusConfigs");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HumitureDevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValidMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValidMin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.HasIndex("HumitureDevicesId");

                    b.ToTable("DataPoints");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPointRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataPointId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataPointId");

                    b.HasIndex("IsValid")
                        .HasFilter("[IsValid] = 1");

                    b.ToTable("DataPointRecords");
                });

            modelBuilder.Entity("MonitorLibrary.Models.HumitureDevices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SerialPortConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("SerialPortConfigId");

                    b.ToTable("HumitureDevices");
                });

            modelBuilder.Entity("MonitorLibrary.Models.SerialPortConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaudRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataBits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("DeviceAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopBits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortName")
                        .IsUnique();

                    b.ToTable("SerialPortConfigs");
                });

            modelBuilder.Entity("ModbusConfig", b =>
                {
                    b.HasOne("MonitorLibrary.Models.DataPoint", null)
                        .WithOne("ModbusConfig")
                        .HasForeignKey("ModbusConfig", "DataPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.HasOne("MonitorLibrary.Models.HumitureDevices", "HumitureDevices")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitorLibrary.Models.HumitureDevices", null)
                        .WithMany("DataPoints")
                        .HasForeignKey("HumitureDevicesId");

                    b.Navigation("HumitureDevices");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPointRecord", b =>
                {
                    b.HasOne("MonitorLibrary.Models.DataPoint", "DataPoint")
                        .WithMany("Records")
                        .HasForeignKey("DataPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataPoint");
                });

            modelBuilder.Entity("MonitorLibrary.Models.HumitureDevices", b =>
                {
                    b.HasOne("MonitorLibrary.Models.SerialPortConfig", "SerialPortConfig")
                        .WithMany()
                        .HasForeignKey("SerialPortConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerialPortConfig");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.Navigation("ModbusConfig")
                        .IsRequired();

                    b.Navigation("Records");
                });

            modelBuilder.Entity("MonitorLibrary.Models.HumitureDevices", b =>
                {
                    b.Navigation("DataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
