// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorApi.Services;

#nullable disable

namespace MonitorApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107065154_i")]
    partial class i
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValidMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValidMin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.ToTable("DataPoints");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AlarmDelay = 30,
                            Code = "Temp",
                            CollectInterval = 10,
                            DataRetentionDays = 30,
                            DeviceId = 1,
                            EnableAlarm = true,
                            LowerLimit = 10.0m,
                            Name = "温度",
                            Unit = "℃",
                            UpperLimit = 35.0m,
                            ValidMax = 80.0m,
                            ValidMin = -20.0m
                        },
                        new
                        {
                            Id = 3,
                            AlarmDelay = 30,
                            Code = "Temp",
                            CollectInterval = 10,
                            DataRetentionDays = 30,
                            DeviceId = 2,
                            EnableAlarm = true,
                            LowerLimit = 10.0m,
                            Name = "温度",
                            Unit = "℃",
                            UpperLimit = 35.0m,
                            ValidMax = 80.0m,
                            ValidMin = -20.0m
                        });
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPointRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataPointId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataPointId");

                    b.HasIndex("IsValid")
                        .HasFilter("[IsValid] = 1");

                    b.ToTable("DataPointRecords");
                });

            modelBuilder.Entity("MonitorLibrary.Models.HumitureDevices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.ToTable("HumitureDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceCode = "SENSOR-001",
                            Location = "一号车间A区域",
                            Name = "车间温湿度传感器",
                            Remark = "用于监测车间环境温湿度",
                            Status = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            DeviceCode = "SENSOR-002",
                            Location = "一号车间A区域",
                            Name = "车间温湿度传感器",
                            Remark = "用于监测车间环境温湿度",
                            Status = "Normal"
                        });
                });

            modelBuilder.Entity("MonitorLibrary.Models.ModbusConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DataMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("DataPointId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeviceAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endianness")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HumitureDevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegisterLength")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4);

                    b.Property<ushort>("RegisterStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataPointId")
                        .IsUnique();

                    b.HasIndex("HumitureDevicesId");

                    b.ToTable("ModbusConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFormat = "Float32",
                            DataMultiplier = 1.0m,
                            DataPointId = 2,
                            DeviceAddress = (byte)1,
                            Endianness = "BigEndian",
                            FunctionCode = "ReadHoldingRegisters",
                            RegisterLength = 2,
                            RegisterStart = (ushort)0
                        },
                        new
                        {
                            Id = 2,
                            DataFormat = "Float32",
                            DataMultiplier = 1.0m,
                            DataPointId = 2,
                            DeviceAddress = (byte)1,
                            Endianness = "BigEndian",
                            FunctionCode = "ReadHoldingRegisters",
                            RegisterLength = 2,
                            RegisterStart = (ushort)0
                        },
                        new
                        {
                            Id = 3,
                            DataFormat = "Float32",
                            DataMultiplier = 1.0m,
                            DataPointId = 3,
                            DeviceAddress = (byte)1,
                            Endianness = "BigEndian",
                            FunctionCode = "ReadHoldingRegisters",
                            RegisterLength = 2,
                            RegisterStart = (ushort)0
                        });
                });

            modelBuilder.Entity("MonitorLibrary.Models.SerialPortConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaudRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataBits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopBits")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("PortName")
                        .IsUnique();

                    b.ToTable("SerialPortConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaudRate = "B9600",
                            DataBits = "Eight",
                            DeviceId = 1,
                            Parity = "None",
                            PortName = "COM3",
                            StopBits = "One",
                            Timeout = 1000
                        },
                        new
                        {
                            Id = 2,
                            BaudRate = "B9600",
                            DataBits = "Eight",
                            DeviceId = 2,
                            Parity = "None",
                            PortName = "COM2",
                            StopBits = "One",
                            Timeout = 1000
                        });
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.HasOne("MonitorLibrary.Models.HumitureDevices", "HumitureDevices")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumitureDevices");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPointRecord", b =>
                {
                    b.HasOne("MonitorLibrary.Models.DataPoint", "DataPoint")
                        .WithMany("Records")
                        .HasForeignKey("DataPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataPoint");
                });

            modelBuilder.Entity("MonitorLibrary.Models.ModbusConfig", b =>
                {
                    b.HasOne("MonitorLibrary.Models.DataPoint", "DataPoint")
                        .WithOne("ModbusConfig")
                        .HasForeignKey("MonitorLibrary.Models.ModbusConfig", "DataPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitorLibrary.Models.HumitureDevices", null)
                        .WithMany("ModbusConfigs")
                        .HasForeignKey("HumitureDevicesId");

                    b.Navigation("DataPoint");
                });

            modelBuilder.Entity("MonitorLibrary.Models.SerialPortConfig", b =>
                {
                    b.HasOne("MonitorLibrary.Models.HumitureDevices", "HumitureDevices")
                        .WithOne("SerialPortConfig")
                        .HasForeignKey("MonitorLibrary.Models.SerialPortConfig", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumitureDevices");
                });

            modelBuilder.Entity("MonitorLibrary.Models.DataPoint", b =>
                {
                    b.Navigation("ModbusConfig")
                        .IsRequired();

                    b.Navigation("Records");
                });

            modelBuilder.Entity("MonitorLibrary.Models.HumitureDevices", b =>
                {
                    b.Navigation("ModbusConfigs");

                    b.Navigation("SerialPortConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
